using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bayer.Ultra.BSL.Approval
{
    public partial class ApprovalContext : Framework.Database.UltraDbContext
    {
        #region [ Attach File ]

        public const string USP_INSERT_EVENT_ATTACH_FILES = "[dbo].[USP_INSERT_EVENT_ATTACH_FILES] @PROCESS_ID, @ATTACH_FILE_TYPE, @SEQ, @REFER_IDX, @DISPLAY_FILE_NAME, @SAVED_FILE_NAME, @FILE_SIZE, @FILE_PATH, @FILE_HANDLER_URL, @IS_DELETED, @CREATOR_ID";

        public const string USP_DELETE_EVENT_ATTACH_FILES = "[dbo].[USP_DELETE_EVENT_ATTACH_FILES] @IDX, @UPDATER_ID";

        public const string USP_SELECT_EVENT_ATTACH_FILES = "[dbo].[USP_SELECT_EVENT_ATTACH_FILES] @PROCESS_ID";

        public const string USP_SELECT_EVENT_ATTACH_FILES_IDXS = "[dbo].[USP_SELECT_EVENT_ATTACH_FILES_IDXS] @PROCESS_ID, @IDX";

        #endregion

        #region Product Briefing

        public const string USP_MERGE_EVENT_PRODUCT_BRIEFING = "[dbo].[USP_MERGE_EVENT_PRODUCT_BRIEFING] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @START_TIME, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

        public const string USP_SELECT_EVENT_PRODUCT_BRIEFING = "[dbo].[USP_SELECT_EVENT_PRODUCT_BRIEFING] @PROCESS_ID";

        public const string USP_INSERT_EVENT_PRODUCT_BRIEFING_PRODUCT = "[dbo].[USP_INSERT_EVENT_PRODUCT_BRIEFING_PRODUCT] @PROCESS_ID, @PRODUCT_IDX, @PRODUCT_CODE, @PRODUCT_NAME, @PRODUCT_TYPE, @IS_DELETED, @CREATOR_ID";

        public const string USP_DELETE_EVENT_PRODUCT_BRIEFING_PRODUCT_ALL = "[dbo].[USP_DELETE_EVENT_PRODUCT_BRIEFING_PRODUCT_ALL] @PROCESS_ID, @UPDATER_ID";

        public const string USP_SELECT_EVENT_PRODUCT_BRIEFING_PRODUCT = "[dbo].[USP_SELECT_EVENT_PRODUCT_BRIEFING_PRODUCT] @PROCESS_ID";

        #endregion

        #region [ Product Seminar ] 

        #region [ USP_MERGE_EVENT_PRODUCT_SEMINAR ]
        public const string USP_MERGE_EVENT_PRODUCT_SEMINAR = "[dbo].[USP_MERGE_EVENT_PRODUCT_SEMINAR] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @START_TIME, @ADDRESS_OF_VENUE, @VENUE_SELECTION_REASON, @VENUE_SELECTION_REASON_MANUAL, @PURPOSE_OBJECTIVE, @COST_PLAN, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";
        #endregion

        #region [ USP_SELECT_EVENT_PRODUCT_SEMINAR ]
        public const string USP_SELECT_EVENT_PRODUCT_SEMINAR = "[dbo].[USP_SELECT_EVENT_PRODUCT_SEMINAR] @PROCESS_ID";
        #endregion

        #region [ USP_INSERT_EVENT_PRODUCT_SEMINAR_PRODUCT ]
        public const string USP_INSERT_EVENT_PRODUCT_SEMINAR_PRODUCT = "[dbo].[USP_INSERT_EVENT_PRODUCT_SEMINAR_PRODUCT] @PROCESS_ID, @PRODUCT_IDX, @PRODUCT_CODE, @PRODUCT_NAME, @PRODUCT_TYPE, @IS_DELETED, @CREATOR_ID";
        #endregion

        #region [ USP_DELETE_EVENT_PRODUCT_SEMINAR_PRODUCT_ALL ]
        public const string USP_DELETE_EVENT_PRODUCT_SEMINAR_PRODUCT_ALL = "[dbo].[USP_DELETE_EVENT_PRODUCT_SEMINAR_PRODUCT_ALL] @PROCESS_ID, @UPDATER_ID";
        #endregion

        #region [ USP_SELECT_EVENT_PRODUCT_SEMINAR_PRODUCT ]
        public const string USP_SELECT_EVENT_PRODUCT_SEMINAR_PRODUCT = "[dbo].[USP_SELECT_EVENT_PRODUCT_SEMINAR_PRODUCT] @PROCESS_ID";
        #endregion

        #endregion

        #region [ Product Presentation Meeting ]

        #region [ USP_MERGE_EVENT_PRODUCT_PRESENTATION ]
        public const string USP_MERGE_EVENT_PRODUCT_PRESENTATION = "[dbo].[USP_MERGE_EVENT_PRODUCT_PRESENTATION] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @START_TIME, @END_TIME, @KRPIA_NUMBER, @ADDRESS_OF_VENUE, @VENUE_SELECTION_REASON, @VENUE_SELECTION_REASON_MANUAL, @ESTIMATED_GO, @ESTIMATED_PUBLIC, @ESTIMATED_PRIVATE, @ESTIMATED_OTHER, @ESTIMATED_FOREIGNER, @ESTIMATED_BAYER, @PURPOSE_OBJECTIVE, @COST_PLAN, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";
        #endregion

        #region [ USP_SELECT_EVENT_PRODUCT_PRESENTATION ]
        public const string USP_SELECT_EVENT_PRODUCT_PRESENTATION = "[dbo].[USP_SELECT_EVENT_PRODUCT_PRESENTATION] @PROCESS_ID";
        #endregion

        #region [ USP_INSERT_EVENT_PRODUCT_PRESENTATION_PRODUCT ]
        public const string USP_INSERT_EVENT_PRODUCT_PRESENTATION_PRODUCT = "[dbo].[USP_INSERT_EVENT_PRODUCT_PRESENTATION_PRODUCT] @PROCESS_ID, @PRODUCT_IDX, @PRODUCT_CODE, @PRODUCT_NAME, @PRODUCT_TYPE, @IS_DELETED, @CREATOR_ID";
        #endregion

        #region [ USP_DELETE_EVENT_PRODUCT_PRESENTATION_PRODUCT_ALL ]
        public const string USP_DELETE_EVENT_PRODUCT_PRESENTATION_PRODUCT_ALL = "[dbo].[USP_DELETE_EVENT_PRODUCT_PRESENTATION_PRODUCT_ALL] @PROCESS_ID, @UPDATER_ID";
        #endregion

        #region [ USP_SELECT_EVENT_PRODUCT_PRESENTATION_PRODUCT ]
        public const string USP_SELECT_EVENT_PRODUCT_PRESENTATION_PRODUCT = "[dbo].[USP_SELECT_EVENT_PRODUCT_PRESENTATION_PRODUCT] @PROCESS_ID";
        #endregion


        #endregion

        #region [ Scientific Exchanged Meeting ]

        public const string USP_MERGE_EVENT_SCIENTIFIC_MEETING = "[dbo].[USP_MERGE_EVENT_SCIENTIFIC_MEETING] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @START_TIME, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

        public const string USP_SELECT_EVENT_SCIENTIFIC_MEETING = "[dbo].[USP_SELECT_EVENT_SCIENTIFIC_MEETING] @PROCESS_ID";

        public const string USP_INSERT_EVENT_SCIENTIFIC_MEETING_PRODUCT = "[dbo].[USP_INSERT_EVENT_SCIENTIFIC_MEETING_PRODUCT] @PROCESS_ID, @PRODUCT_IDX, @PRODUCT_CODE, @PRODUCT_NAME, @PRODUCT_TYPE, @IS_DELETED, @CREATOR_ID";

        public const string USP_DELETE_EVENT_SCIENTIFIC_MEETING_PRODUCT_ALL = "[dbo].[USP_DELETE_EVENT_SCIENTIFIC_MEETING_PRODUCT_ALL] @PROCESS_ID, @UPDATER_ID";

        public const string USP_SELECT_EVENT_SCIENTIFIC_MEETING_PRODUCT = "[dbo].[USP_SELECT_EVENT_SCIENTIFIC_MEETING_PRODUCT] @PROCESS_ID";

		#endregion

        #region [ Free Good ]

        public const string USP_SELECT_EVENT_FREE_GOOD = "[dbo].[USP_SELECT_EVENT_FREE_GOOD] @PROCESS_ID";

        public const string USP_SELECT_EVENT_FREE_GOOD_HCP = "[dbo].[USP_SELECT_EVENT_FREE_GOOD_HCP] @PROCESS_ID, @TYPE";

        public const string USP_INSERT_EVENT_FREE_GOOD = "[dbo].[USP_INSERT_EVENT_FREE_GOOD] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @PURPOSE, @LOCATION, @IMPACT_NO, @PO_NO, @COMMENT,@DELIVER_DATE ,@RETURN_DATE , @IS_DISUSED,  @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_MERGE_EVENT_FREE_GOOD_HCP = "[dbo].[USP_MERGE_EVENT_FREE_GOOD_HCP] @PROCESS_ID, @IDX, @HCP_CODE, @TYPE,@SPECIALITY, @HCP_NAME, @HCO_CODE, @HCO_NAME, @PRODUCT_CODE, @PRODUCT_NAME, @SAMPLE_CODE, @QTY, @IS_DELETED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_SELECT_EXISTS_FREE_GOOD_HCP_SAMPLE = "[dbo].[USP_SELECT_EXISTS_FREE_GOOD_HCP_SAMPLE] @PROCESS_ID, @HCP_CODE, @HCO_CODE, @SAMPLE_CODE, @TYPE";

        public const string USP_DELETE_EVENT_FREE_GOOD_HCP = "[dbo].[USP_DELETE_EVENT_FREE_GOOD_HCP] @PROCESS_ID";

        public const string USP_SELECT_EVENT_FREE_GOOD_HCP_EXISTS = "[dbo].[USP_SELECT_EVENT_FREE_GOOD_HCP_EXISTS] @HCP_CODE, @HCP_NAME, @HCO_CODE, @SAMPLE_CODE";
        public const string USP_SELECT_EVENT_FREE_GOOD_HCP_EXISTS_RAD = "[dbo].[USP_SELECT_EVENT_FREE_GOOD_HCP_EXISTS_RAD] @HCP_CODE, @HCP_NAME, @HCO_CODE, @SAMPLE_CODE";
        #endregion

        #region [ Clinical Related Meeting ]
        public const string USP_MERGE_EVENT_CLINICAL_MEETING = "[dbo].[USP_MERGE_EVENT_CLINICAL_MEETING] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @CATEGORY, @IMPACT_NO, @START_TIME, @ADDRESS_OF_VENUE, @VENUE_SELECTION_REASON, @VENUE_SELECTION_REASON_MANUAL, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

		public const string USP_SELECT_EVENT_CLINICAL_MEETING = "[dbo].[USP_SELECT_EVENT_CLINICAL_MEETING] @PROCESS_ID";
		#endregion

		#region [ Congress Events ]
		public const string USP_MERGE_EVENT_CONGRESS = "[dbo].[USP_MERGE_EVENT_CONGRESS] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @START_TIME, @END_TIME, @VENUE, @HOST, @PAYMENT_TO, @PARTICIPANT_COUNT, @KRPIA_NUMBER, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

		public const string USP_SELECT_EVENT_CONGRESS = "[dbo].[USP_SELECT_EVENT_CONGRESS] @PROCESS_ID";
		#endregion

		#region [ Adventisement / booth ]
		public const string USP_MERGE_EVENT_ADVENTISEMENT = "[dbo].[USP_MERGE_EVENT_ADVENTISEMENT] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @START_TIME, @END_TIME, @HOST, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

		public const string USP_SELECT_EVENT_ADVENTISEMENT = "[dbo].[USP_SELECT_EVENT_ADVENTISEMENT] @PROCESS_ID";
		#endregion

		#region [ Employee Medical Training (EMT) ] 

		public const string USP_MERGE_EVENT_EMPLOYEE_TRAINING = "[dbo].[USP_MERGE_EVENT_EMPLOYEE_TRAINING] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @START_TIME, @END_TIME, @ADDRESS_OF_VENUE, @VENUE_SELECTION_REASON, @VENUE_SELECTION_REASON_MANUAL, @COST_PLAN, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

		public const string USP_SELECT_EVENT_EMPLOYEE_TRAINING = "[dbo].[USP_SELECT_EVENT_EMPLOYEE_TRAINING] @PROCESS_ID";
        #endregion

        #region [ Consulting/ABM(Medical MSL) Meeting ] 
        //version 1.0.6 ABM 문서에 Category
        //public const string USP_MERGE_EVENT_CONSULTING_MEETING = "[dbo].[USP_MERGE_EVENT_CONSULTING_MEETING] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE @START_TIME, @END_TIME, @ADDRESS_OF_VENUE, @VENUE_SELECTION_REASON, @VENUE_SELECTION_REASON_MANUAL, @PURPOSE_OBJECTIVE, @COST_PLAN,@COMPLIANCE_1,@COMPLIANCE_2,@COMPLIANCE_REASON_1,@COMPLIANCE_REASON_2, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

        public const string USP_MERGE_EVENT_CONSULTING_MEETING = "[dbo].[USP_MERGE_EVENT_CONSULTING_MEETING] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE,@CATEGORY, @START_TIME, @END_TIME, @ADDRESS_OF_VENUE, @VENUE_SELECTION_REASON, @VENUE_SELECTION_REASON_MANUAL, @PURPOSE_OBJECTIVE, @COST_PLAN,@COMPLIANCE_1,@COMPLIANCE_2,@COMPLIANCE_REASON_1,@COMPLIANCE_REASON_2, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

        public const string USP_SELECT_EVENT_CONSULTING_MEETING = "[dbo].[USP_SELECT_EVENT_CONSULTING_MEETING] @PROCESS_ID";

		#endregion

		#region [ Donation ] 

		public const string USP_MERGE_EVENT_DONATION = "[dbo].[USP_MERGE_EVENT_DONATION] @PROCESS_ID, @SUBJECT, @EVENT_KEY, @PROCESS_STATUS, @REQUESTER_ID, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @VALUE, @PURPOSE, @EXPLANATION, @RECIPIENT, @ADDRESS, @TEL, @EMAIL, @IS_ELIGIBILITY, @AFTER_RECEIPT, @COMMENT, @CATEGORY, @IS_DISUSED, @CREATOR_ID, @UPDATER_ID";

		public const string USP_SELECT_EVENT_DONATION = "[dbo].[USP_SELECT_EVENT_DONATION] @PROCESS_ID";

        public const string USP_INSERT_EVENT_DONATION_PRODUCT = "[dbo].[USP_INSERT_EVENT_DONATION_PRODUCT] @PROCESS_ID, @PRODUCT_IDX, @BU, @PRODUCT_CODE, @PRODUCT_NAME, @BASE_PRICE, @QTY, @AMOUNT, @IS_DELETED, @CREATOR_ID";

        public const string USP_DELETE_EVENT_DONATION_PRODUCT_ALL = "[dbo].[USP_DELETE_EVENT_DONATION_PRODUCT_ALL] @PROCESS_ID, @UPDATER_ID";

        public const string USP_SELECT_EVENT_DONATION_PRODUCT = "[dbo].[USP_SELECT_EVENT_DONATION_PRODUCT] @PROCESS_ID";

        #endregion
	}
}
